# Setup
title:            Topología aplicada
tagline:          'LIMA, UAEH, 2021'
description:      'LIMA, UAEH, 2021'
url:              "http://rvf0068.github.com/topologia-aplicada"
baseurl:          "/topologia-aplicada"

author:
  name:           'Rafael Villarroel'
  url:            https://twitter.com/rvf0068

paginate:         5

# Custom vars
github:
  repo:           https://github.com/rvf0068/topologia-aplicada

thepage:          https://github.com/rvf0068/topologia-aplicada

plugins:          [jekyll-paginate]

language:         spanish

disqus:           mateclases.disqus.com/embed.js

# see https://github.com/github/pages-gem/issues/399#issuecomment-301827749
github:           [metadata]